src/Entity/Event.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EventRepository")
 */
class Event
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=144)
     */
    private $image;

    /**
     * @ORM\Column(type="datetime")
     */
    private $StartDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $EndDate;

    /**
     * @ORM\Column(type="string", length=160)
     */
    private $venue;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $news;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isPublished;

    public function getId()
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->StartDate;
    }

    public function setStartDate(\DateTimeInterface $StartDate): self
    {
        $this->StartDate = $StartDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->EndDate;
    }

    public function setEndDate(\DateTimeInterface $EndDate): self
    {
        $this->EndDate = $EndDate;

        return $this;
    }

    public function getVenue(): ?string
    {
        return $this->venue;
    }

    public function setVenue(string $venue): self
    {
        $this->venue = $venue;

        return $this;
    }

    public function getNews(): ?string
    {
        return $this->news;
    }

    public function setNews(?string $news): self
    {
        $this->news = $news;

        return $this;
    }

    public function getIsPublished(): ?bool
    {
        return $this->isPublished;
    }

    public function setIsPublished(bool $isPublished): self
    {
        $this->isPublished = $isPublished;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Agenda | {% endblock %}</title>

        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="/css/bootstrap.min.css">
    
        <!-- FontAwesome CSS -->
        <link rel="stylesheet" href="/css/font-awesome.min.css">
    
        <!-- Swiper CSS -->
        <link rel="stylesheet" href="/css/swiper.min.css">
    
        <!-- Styles -->
        <link rel="stylesheet" href="/style.css">
        {% block stylesheets %}{% endblock %}
        
    </head>
    {% block bodytag %}<body>{% endblock %}
        <header class="site-header">
        <div class="header-bar">
            <div class="container-fluid">
                <div class="row align-items-center">
                    <div class="col-10 col-lg-2 order-lg-1">
                        <div class="site-branding">
                            <div class="site-title">
                                <a href="{{ path('home') }}"><img src="images/logo.png" alt="logo"></a>
                            </div><!-- .site-title -->
                        </div><!-- .site-branding -->
                    </div><!-- .col -->
    
                    <div class="col-2 col-lg-7 order-3 order-lg-2">
                        <nav class="site-navigation">
                            <div class="hamburger-menu d-lg-none">
                                <span></span>
                                <span></span>
                                <span></span>
                                <span></span>
                            </div><!-- .hamburger-menu -->
    
                            <ul> {# navigation to the different routes #}
                                <li><a href="{{ path('home') }}">Home</a></li>
                                <li><a href="{{ path('home') }}#about-us">About us</a></li>  {# the link is situated on the home page in an anchor tag #}
                                <li><a href="{{ path('events') }}">Events</a></li>
                                <li><a href="{{ path('news') }}">News</a></li>
                                <li><a href="{{ path('contact') }}">Contact</a></li>
                            </ul>
                        </nav><!-- .site-navigation -->
                    </div><!-- .col -->
    
                    <div class="col-lg-3 d-none d-lg-block order-2 order-lg-3">
                        <div class="buy-tickets">
                            <a class="btn gradient-bg" href="{{ path('events') }}">Buy Tickets</a>
                        </div><!-- .buy-tickets -->
                    </div><!-- .col -->
                </div><!-- .row -->
            </div><!-- .container-fluid -->
        </div><!-- .header-bar -->
    
        <!-- end of common header -->
        
     
        {% block body %}{% endblock %}
        
        <!--  Newsletter and footer -->
        <div class="newsletter-subscribe">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <header class="entry-header">
                            <h2 class="entry-title">Subscribe to our newsletter to get the latest trends & news</h2>
                            <p>Join our database NOW!</p>
                        </header>
                        <a name="newsletter"></a>
                        <div class="newsletter-form">
                        {# renders the newsletter controller that will render form/registrationform.html.twig #}
                        {{ render(controller(
                        'App\\Controller\\DefaultController::newsletter'
                        )) }}
                        
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <footer class="site-footer">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <figure class="footer-logo">
                            <a href="#"><img src="images/logo.png" alt="logo"></a>
                        </figure>
        
                        <nav class="footer-navigation">  {# footer navigation to the different routes #}
                            <ul class="flex flex-wrap justify-content-center align-items-center">
                                <li><a href="{{ path('home') }}">Home</a></li>
                                <li><a href="{{ path('home') }}#about-us">About us</a></li> {# the link is situated on the home page in an anchor tag #}
                                <li><a href="{{ path('events') }}">Events</a></li>
                                <li><a href="{{ path('news') }}">News</a></li>
                                <li><a href="{{ path('contact') }}">Contact</a></li>
                            </ul>
                        </nav>
        
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
        Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
        
                        <div class="footer-social">
                            <ul class="flex flex-wrap justify-content-center align-items-center">
                                <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
                                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                                <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        
        
        
        <div class="back-to-top flex justify-content-center align-items-center">
            <span><svg viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg"><path d="M1395 1184q0 13-10 23l-50 50q-10 10-23 10t-23-10l-393-393-393 393q-10 10-23 10t-23-10l-50-50q-10-10-10-23t10-23l466-466q10-10 23-10t23 10l466 466q10 10 10 23z"/></svg></span>
        </div>
        
        <script type='text/javascript' src='/js/jquery.js'></script>
        <script type='text/javascript' src='/js/masonry.pkgd.min.js'></script>
        <script type='text/javascript' src='/js/jquery.collapsible.min.js'></script>
        <script type='text/javascript' src='/js/swiper.min.js'></script>
        <script type='text/javascript' src='/js/jquery.countdown.min.js'></script>
        <script type='text/javascript' src='/js/circle-progress.min.js'></script>
        <script type='text/javascript' src='/js/jquery.countTo.min.js'></script>
        <script type='text/javascript' src='/js/custom.js'></script>
        <script type='text/javascript'>
/*         jQuery(document).ready(function(){
        	alert("success");
            }) */
            </script>
     
    
    </body>
</html>

templates/contact.html.twig
{% extends 'base.html.twig' %}
{% block title %}Contact{% endblock %}
{% block bodytag %}<body class="contact-page">{% endblock %}

{% block body %} 

    <div class="page-header contact-page-header">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <header class="entry-header">
                    
                        <!--this includes flash messages success/failure after submitting the contact form -->  
       {% include 'flash_messages.html.twig' %}
  
                        <h1 class="entry-title">Contact</h1>
                    </header>
                </div>
            </div>
        </div>
    </div>
</header><!-- .site-header -->

<div class="container">
    <div class="row">
        <div class="col-12 col-md-6 col-lg-4">
            <div class="contact-location-details">
                <h2 class="entry-title">New York</h2>

                <div class="entry-content">
                    <p>Vestibulum eget lacus at mauris sagittis varius. Etiam ut venenatis dui. Nullam tellus risus, pellentesque at facilisis et.</p>
                </div>

                <footer class="entry-footer">
                    <ul>
                        <li class="contact-address">667889 Madison Avenue, no24-56</li>
                        <li class="contact-number">665 5667 8899 661</li>
                        <li class="contact-email"><a href="#">office@yourbusiness.com</a></li>
                    </ul>
                </footer>
            </div>
        </div>

        <div class="col-12 col-md-6 col-lg-4">
            <div class="contact-location-details">
                <h2 class="entry-title">Miami</h2>

                <div class="entry-content">
                    <p>Vestibulum eget lacus at mauris sagittis varius. Etiam ut venenatis dui. Nullam tellus risus, pellentesque at facilisis et.</p>
                </div>

                <footer class="entry-footer">
                    <ul>
                        <li class="contact-address">122344 Island Str, no23</li>
                        <li class="contact-number">665 5667 8899 661</li>
                        <li class="contact-email"><a href="#">office@yourbusiness.com</a></li>
                    </ul>
                </footer>
            </div>
        </div>

        <div class="col-12 col-md-6 col-lg-4">
            <div class="contact-location-details">
                <h2 class="entry-title">Los Angeles</h2>

                <div class="entry-content">
                    <p>Vestibulum eget lacus at mauris sagittis varius. Etiam ut venenatis dui. Nullam tellus risus, pellentesque at facilisis et.</p>
                </div>

                <footer class="entry-footer">
                    <ul>
                        <li class="contact-address">667889 Long Avenue, no24-56</li>
                        <li class="contact-number">665 5667 8899 661</li>
                        <li class="contact-email"><a href="#">office@yourbusiness.com</a></li>
                    </ul>
                </footer>
            </div>
        </div>
    </div>
</div>

<div class="contact-page-map">
    <iframe id="gmap_canvas" src="https://maps.google.com/maps?q=university of san francisco&t=&z=15&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
</div>

<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="contact-form">
            
            {% include 'form/contactform.html.twig' %}
                
            </div>
        </div>
    </div>
</div>
  
{% endblock %}

templates/events.html.twig
{% extends 'base.html.twig' %}
{% block title %}Events{% endblock %}
{% block bodytag %}<body class="events-list-page">{% endblock %}
{% block body %} 

    <div class="page-header events-page-header">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <header class="entry-header">
                     
                     <!--this includes flash messages success/failure after submitting the contact form -->  
       {% include 'flash_messages.html.twig' %}
       
                        <h1 class="entry-title">Events</h1>
                    </header>
                </div>
            </div>
        </div>
    </div>
</header><!-- .site-header -->

<form class="events-search" action="{{ path('events') }}" method="post">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-3">
                <input type="date" placeholder="Date" name="date">
            </div>

            <div class="col-12 col-md-3">
                <input type="text" placeholder="Event" name="event">
            </div>

            <div class="col-12 col-md-3">
                <input type="text" placeholder="Location" name="venue">
            </div>

            <div class="col-12 col-md-3">
                <input class="btn gradient-bg" type="submit" value="Search Events">
            </div>
        </div>
    </div>
</form>

<div class="container">
    <div class="row events-list">
    {% for event in events %} {# loop through events #}
    {# single event #}
        <div class="col-12 col-lg-6 single-event">
            <figure class="events-thumbnail">
                <a href="#"><img src="{{ event.image }}" alt=""></a>
            </figure>

            <div class="event-content-wrap">
                <header class="entry-header flex justify-content-between">
                    <div>
                        <h2 class="entry-title">{{ event.title }}</h2>

                        <div class="event-location">{{ event.venue }}</div>
                          
                           {# formatting the date #}
                        <div class="event-date">{{ event.startDate|date("M, d, Y") }} @ {{ event.startDate|date("g:i A") }} - {{ event.endDate|date("M, d, Y") }} @ {{ event.endDate|date("g:i A") }}</div>
                    </div>

                    <div class="event-cost flex justify-content-center align-items-center">
                        from<span>$89</span>
                    </div>
                </header>

                <footer class="entry-footer">
                    <a href="#">Buy Tikets</a>
                </footer>
            </div>
        </div>
        {# end of single event #}
        {% endfor %}
        
      

        
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="load-more-btn">
                <a class="btn gradient-bg" href="#">Load More</a>
            </div>
        </div>
    </div>
</div>

<div class="upcoming-events-outer">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="upcoming-events">
                    <div class="upcoming-events-header">
                        <h4>Upcoming Events</h4>
                    </div>

                    <div class="upcoming-events-list">
                        <div class="upcoming-event-wrap flex flex-wrap justify-content-between align-items-center">
                            <figure class="events-thumbnail">
                                <a href="#"><img src="images/upcoming-1.jpg" alt=""></a>
                            </figure>

                            <div class="entry-meta">
                                <div class="event-date">
                                    25<span>February</span>
                                </div>
                            </div>

                            <header class="entry-header">
                                <h3 class="entry-title"><a href="#">Blockchain Conference</a></h3>

                                <div class="event-date-time">May 29, 2018 @ 8:00 Pm - May 30, 2018 @ 4:00 Am</div>

                                <div class="event-speaker">Speackers: Maria Williams, Luis Smith, James Doe</div>
                            </header>

                            <footer class="entry-footer">
                                <a href="#">Buy Tikets</a>
                            </footer>
                        </div>

                        <div class="upcoming-event-wrap flex flex-wrap justify-content-between align-items-center">
                            <figure class="events-thumbnail">
                                <a href="#"><img src="images/upcoming-2.jpg" alt=""></a>
                            </figure>

                            <div class="entry-meta">
                                <div class="event-date">
                                    27<span>February</span>
                                </div>
                            </div>

                            <header class="entry-header">
                                <h3 class="entry-title"><a href="#">Financial Conference</a></h3>

                                <div class="event-date-time">May 29, 2018 @ 8:00 Pm - May 30, 2018 @ 4:00 Am</div>

                                <div class="event-speaker">Speackers: Maria Williams, Luis Smith, James Doe</div>
                            </header>

                            <footer class="entry-footer">
                                <a href="#">Buy Tikets</a>
                            </footer>
                        </div>

                        <div class="upcoming-event-wrap flex flex-wrap justify-content-between align-items-center">
                            <figure class="events-thumbnail">
                                <a href="#"><img src="images/upcoming-3.jpg" alt=""></a>
                            </figure>

                            <div class="entry-meta">
                                <div class="event-date">
                                    27<span>February</span>
                                </div>
                            </div>

                            <header class="entry-header">
                                <h3 class="entry-title"><a href="#">Winter Festival</a></h3>

                                <div class="event-date-time">May 29, 2018 @ 8:00 Pm - May 30, 2018 @ 4:00 Am</div>

                                <div class="event-speaker">Speackers: Maria Williams, Luis Smith, James Doe</div>
                            </header>

                            <footer class="entry-footer">
                                <a href="#">Buy Tikets</a>
                            </footer>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

  
{% endblock %}

templates/flash_messages.html.twig
{% block flash_messages %}
    {% for type, messages in app.session.flashbag.all() %}
        {% for message in messages %}
            <div class="alert alert-{{ type }} alert-dismissible" role="alert">
               <!--  <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button> -->
                {{ message | raw }}
            </div>
        {% endfor %}
    {% endfor %}
{% endblock %}

templates/news.html.twig
{% extends 'base.html.twig' %}
{% block title %}Home{% endblock %}
{% block bodytag %}<body class="events-news-page">{% endblock %}
{% block body %} 

    <div class="page-header events-news-page-header">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <header class="entry-header">
                        <h1 class="entry-title">Events news.</h1>
                    </header>
                </div>
            </div>
        </div>
    </div>
</header><!-- .site-header -->

<div class="container">
    <div class="row">
        <div class="col-12">
            <article class="events-news-post">
                <header class="entry-header">
                    <h2 class="entry-title"><a href="#">A guide to all summer festivals</a></h2>

                    <div class="entry-meta flex align-items-center">
                        <div class="posted-author"><a href="#">by James Williams</a></div>

                        <div class="post-comments"><a href="#">2 Comments</a></div>
                    </div>
                </header>

                <figure>
                    <a href="#"><img src="images/news-1.jpg" alt=""></a>

                    <div class="posted-date"><span>Feb</span><span>11</span><span>‘18</span></div>
                </figure>

                <div class="entry-content">
                    <p>Vestibulum eget lacus at mauris sagittis varius. Etiam ut venenatis dui. Nullam tellus risus, pellentesque at facilisis et, scelerisque sit amet metus. Duis vel semper turpis, ac tempus libero. Maecenas id ultrices risus. Aenean nec ornare ipsum, lacinia volutpat urna. Maecenas ut aliquam purus, quis sodales dolor.tiam ut venenatis dui. Nullam tellus risus, pellentesque at facilisis et, scelerisque sit ame.</p>
                </div>
            </article>

            <article class="events-news-post">
                <header class="entry-header">
                    <h2 class="entry-title"><a href="#">Top 10 electronic music events in February</a></h2>

                    <div class="entry-meta flex align-items-center">
                        <div class="posted-author"><a href="#">by James Williams</a></div>

                        <div class="post-comments"><a href="#">2 Comments</a></div>
                    </div>
                </header>

                <figure>
                    <a href="#"><img src="images/news-2.jpg" alt=""></a>

                    <div class="posted-date"><span>Feb</span><span>11</span><span>‘18</span></div>
                </figure>

                <div class="entry-content">
                    <p>Vestibulum eget lacus at mauris sagittis varius. Etiam ut venenatis dui. Nullam tellus risus, pellentesque at facilisis et, scelerisque sit amet metus. Duis vel semper turpis, ac tempus libero. Maecenas id ultrices risus. Aenean nec ornare ipsum, lacinia volutpat urna. Maecenas ut aliquam purus, quis sodales dolor.tiam ut venenatis dui. Nullam tellus risus, pellentesque at facilisis et, scelerisque sit ame.</p>
                </div>
            </article>

            <article class="events-news-post">
                <header class="entry-header">
                    <h2 class="entry-title"><a href="#">Must-see events this summer</a></h2>

                    <div class="entry-meta flex align-items-center">
                        <div class="posted-author"><a href="#">by James Williams</a></div>

                        <div class="post-comments"><a href="#">2 Comments</a></div>
                    </div>
                </header>

                <figure>
                    <a href="#"><img src="images/news-3.jpg" alt=""></a>

                    <div class="posted-date"><span>Feb</span><span>11</span><span>‘18</span></div>
                </figure>

                <div class="entry-content">
                    <p>Vestibulum eget lacus at mauris sagittis varius. Etiam ut venenatis dui. Nullam tellus risus, pellentesque at facilisis et, scelerisque sit amet metus. Duis vel semper turpis, ac tempus libero. Maecenas id ultrices risus. Aenean nec ornare ipsum, lacinia volutpat urna. Maecenas ut aliquam purus, quis sodales dolor.tiam ut venenatis dui. Nullam tellus risus, pellentesque at facilisis et, scelerisque sit ame.</p>
                </div>
            </article>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="blog-pagination">
                <ul class="flex align-items-center">
                    <li><a href="#">01</a></li>
                    <li class="active"><a href="#">02</a></li>
                    <li><a href="#">03</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
  
{% endblock %}